import Image from "next/image";

export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};


const AboutPage = () => {
    return (
        <div>
            <h1>Our about page</h1>
            <Image src={'/pahar.jpg'} alt="pahar" height={600} width={400}></Image>
            <Image src={'/lion.jpg'} alt="lion" width={400} height={800}></Image>
            <Image src={'/projapoti.jpg'} alt="projapoti" height={300} width={500}></Image>
            <br />
            {/* <Image src={"https://i.ibb.co.com/RT6dMWWC/lion.jpg"} alt="lion" width={300} height={300}></Image>
            <Image src={"https://i.ibb.co.com/pB2FLCtG/Rectangle-8.png"} alt="banner" width={900} height={500}></Image> */}
        </div>
    );
};

export default AboutPage;